# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  rabbitmq-prometheus:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  log_volume:

services:
  booking-one: &booking
    container_name: booking-one
    build:
      context: ./booking
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "LOGGING_FILE=/logs/booking-1-application.log"
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - log_volume:/logs
  booking-two:
    <<: *booking
    container_name: booking-two
    ports:
      - "8101:8100"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "LOGGING_FILE=/logs/booking-2-application.log"
  searching:
    container_name: searching
    build:
      context: ./searching
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "LOGGING_FILE=/logs/searching-application.log"
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - log_volume:/logs
  financial:
    container_name: financial
    build:
      context: ./financial
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "LOGGING_FILE=/logs/financial-application.log"
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - log_volume:/logs